name: Tests

on: push

jobs:
  Tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test

      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}          
          files: src/apps/client/coverage/clover.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
